### ISSUE TITLE
Metadata fileds in the input records 

### ISSUE THREAD

**Issue by Masoumeh** [dasmiq/passim#3]
When I add an extra filed to the input records I get the following error:

`org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 911 tasks (1024.5 MB) is bigger than spark.driver.maxResultSize (1024.0 MB)`

The field is called _unit_ids_ which is a list of string ids. Here is a sample record with the new filed:
`{"id":"JK000223-ara1_logical2.log1", "series":"JK000223-ara1_logical2", "text": " ...", "unit_ids": "['#00001-13 00014-14', '#00015-35', '#00036-57', '#00058-104', '#00105-178', '#00179-200']" }`

Also, there is an error in the partitioning script which might or might not be relevant. I attach both log files. 

[run.txt](https://github.com/dasmiq/passim/files/2159432/run.txt)
[script-pair.txt](https://github.com/dasmiq/passim/files/2159433/script-pair.txt)

**Comment by dasmiq** [comment]
As the error message shows, the problem is not enough memory allocated in the driver. This is an annoyance spark shares with other JVM programs where you need to tell it ahead of time how much memory you'll use. So this is a spark error uncovered by having bigger input records. The fix is to increase that spark.driver.maxResultSize variable with:
export SPARK_SUBMIT_ARGS=" ... --conf spark.driver.maxResultSize=5G ... " or whatever.

Unrelated to that, I see your JSON input encodes an array of strings as a string. Although it doesn't matter to passim since it just passes that record through, you could use an actual array of strings:
..., "unit_ids": ["#00001-13 00014-14", "#00015-35", "#00036-57", "#00058-104", "#00105-178", "#00179-200"], ...
